--- #YAML:1.0
name: Rose-DBx-Object-Renderer
version: 0.28
author:
  - Xufeng (Danny) Liang <danny.glue@gmail.com>
abstract: Web UI Generation for Rose::DB::Object
license: perl
requires:
  Test::More: 0
  Lingua::EN::Inflect: 0
  DateTime: 0
  Rose::DB::Object::Loader: 0
  CGI::FormBuilder: 3.05
  Template: 0
  File::Path: 0
  Digest::MD5: 0
  Math::Round: 0
  File::Copy::Recursive: 0
  Image::ExifTool: 0
