--- #YAML:1.0
name: Rose-DBx-Object-Renderer
version: 0.08
author:
  - Xufeng (Danny) Liang <danny.glue@gmail.com>
abstract: Web UI Rendering for Rose::DB::Object
license: perl
requires:
  Test::More: 0
  Lingua::EN::Inflect: 0
  Data::Dumper: 0
  DateTime: 0
  Rose::DB::Object::Loader: 0
  CGI::FormBuilder: 3.05
  Template: 0
  File::Path: 0
  Digest::MD5: 0
  Math::Round: 0
  File::Copy::Recursive: 0
  Image::ExifTool: 0
  JSON::XS: 2.01
  Tie::Hash::Indexed: 0
